In [1]:
import pandas as pd
import json
from datetime import datetime
pd.set_option('display.max_columns', None)

In [2]:
df_work_raw = catalog.load('raw/openalex/work#parquet')

[02/21/26 12:19:31] INFO     Loading data from raw/openalex/work#parquet (ParquetDataset)...   ]8;id=462079;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=760739;file:///home/pablo/dev/scholar/kedro-scholar/.venv/lib/python3.10/site-packages/kedro/io/data_catalog.py#1048\1048]8;;\

# Profiling

In [3]:
df_work_raw.columns

Index(['id', 'doi', 'title', 'display_name', 'publication_year',
       'publication_date', 'ids', 'language', 'primary_location', 'type',
       'indexed_in', 'open_access', 'authorships', 'institutions',
       'countries_distinct_count', 'institutions_distinct_count',
       'corresponding_author_ids', 'corresponding_institution_ids', 'apc_list',
       'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count',
       'citation_normalized_percentile', 'cited_by_percentile_year', 'biblio',
       'is_retracted', 'is_paratext', 'is_xpac', 'primary_topic', 'topics',
       'keywords', 'concepts', 'mesh', 'locations_count', 'locations',
       'best_oa_location', 'sustainable_development_goals', 'awards',
       'funders', 'has_content', 'referenced_works_count', 'referenced_works',
       'related_works', 'abstract_inverted_index', 'counts_by_year',
       'updated_date', 'created_date', 'extract_datetime'],
      dtype='object')

In [4]:
df_work_raw.head(3)

,id,doi,title,display_name,publication_year,publication_date,ids,language,primary_location,type,indexed_in,open_access,authorships,institutions,countries_distinct_count,institutions_distinct_count,corresponding_author_ids,corresponding_institution_ids,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio,is_retracted,is_paratext,is_xpac,primary_topic,topics,keywords,concepts,mesh,locations_count,locations,best_oa_location,sustainable_development_goals,awards,funders,has_content,referenced_works_count,referenced_works,related_works,abstract_inverted_index,counts_by_year,updated_date,created_date,extract_datetime
0,https://openalex.org/W2140131090,https://doi.org/10.1016/j.foreco.2009.09.001,A global overview of drought and heat-induced ...,A global overview of drought and heat-induced ...,2009,2009-10-22,{'doi': 'https://doi.org/10.1016/j.foreco.2009...,en,"{'id': 'doi:10.1016/j.foreco.2009.09.001', 'is...",article,[crossref],"{'any_repository_has_fulltext': False, 'is_oa'...",[{'affiliations': [{'institution_ids': array([...,[],9,20,[],[],"{'currency': 'USD', 'value': 3460.0, 'value_us...",None,93.387205,False,7330,"{'is_in_top_10_percent': True, 'is_in_top_1_pe...","{'max': 100, 'min': 99}","{'first_page': '660', 'issue': '4', 'last_page...",False,False,False,"{'display_name': 'Fire effects on ecosystems',...",[{'display_name': 'Fire effects on ecosystems'...,"[{'display_name': 'Climate change', 'id': 'htt...","[{'display_name': 'Climate change', 'id': 'htt...",[],4,"[{'id': 'doi:10.1016/j.foreco.2009.09.001', 'i...","{'id': 'pmh:oai:HAL:hal-00457602v1', 'is_accep...","[{'display_name': 'Climate action', 'id': 'htt...",[],[],"{'grobid_xml': False, 'pdf': False}",251,"[https://openalex.org/W2161828152, https://ope...","[https://openalex.org/W4210601336, https://ope...",None,"[{'cited_by_count': 522, 'year': 2025}, {'cite...",2025-11-06T03:46:38.306776,2025-10-10T00:00:00,2025-12-15
1,https://openalex.org/W2762087180,https://doi.org/10.1016/j.cell.2017.09.021,Ferroptosis: A Regulated Cell Death Nexus Link...,Ferroptosis: A Regulated Cell Death Nexus Link...,2017,2017-10-01,{'doi': 'https://doi.org/10.1016/j.cell.2017.0...,en,"{'id': 'doi:10.1016/j.cell.2017.09.021', 'is_a...",review,"[crossref, pubmed]","{'any_repository_has_fulltext': False, 'is_oa'...",[{'affiliations': [{'institution_ids': array([...,[],6,27,[https://openalex.org/A5030207693],[https://openalex.org/I78577930],"{'currency': 'USD', 'value': 10100.0, 'value_u...",None,227.560904,False,6749,"{'is_in_top_10_percent': True, 'is_in_top_1_pe...","{'max': 100, 'min': 90}","{'first_page': '273', 'issue': '2', 'last_page...",False,False,False,{'display_name': 'Ferroptosis and cancer progn...,[{'display_name': 'Ferroptosis and cancer prog...,"[{'display_name': 'Biology', 'id': 'https://op...","[{'display_name': 'Biology', 'id': 'https://op...","[{'descriptor_name': 'Animals', 'descriptor_ui...",6,"[{'id': 'doi:10.1016/j.cell.2017.09.021', 'is_...","{'id': 'doi:10.1016/j.cell.2017.09.021', 'is_a...",[{'display_name': 'Good health and well-being'...,"[{'display_name': None, 'funder_award_id': 'U1...",[{'display_name': 'Geoffrey Beene Cancer Resea...,"{'grobid_xml': True, 'pdf': True}",115,"[https://openalex.org/W2258749495, https://ope...","[https://openalex.org/W3126909309, https://ope...",None,"[{'cited_by_count': 1129, 'year': 2025}, {'cit...",2025-11-06T03:46:38.306776,2025-10-10T00:00:00,2025-12-15
2,https://openalex.org/W2151692850,https://doi.org/10.1111/j.1096-0031.2008.00217.x,"TNT, a free program for phylogenetic analysis","TNT, a free program for phylogenetic analysis",2008,2008-07-11,{'doi': 'https://doi.org/10.1111/j.1096-0031.2...,en,"{'id': 'doi:10.1111/j.1096-0031.2008.00217.x',...",article,[crossref],"{'any_repository_has_fulltext': False, 'is_oa'...",[{'affiliations': [{'institution_ids': array([...,[],3,3,[],[],"{'currency': 'USD', 'value': 3810.0, 'value_us...",None,204.217212,False,5267,"{'is_in_top_10_percent': True, 'is_in_top_1_pe...","{'max': 100, 'min': 99}","{'first_page': '774', 'issue': '5', 'last_page...",False,False,False,{'display_name': 'Plant Diversity and Evolutio...,[{'display_name': 'Plant Diversity and Evoluti...,"[{'display_name': 'Scripting language', 'id': ...","[{'display_name': 'Scripting language', 'id': ...",[],4,[{'id': 'doi:10.1111/j.1096-0031.2008.00217.x'...,"{'id': 'doi:10.1111/j.1096-0031.2008.00217.x',...",[],[],[],"{'grobid_xml': True, 'pdf': True}",38,"[https://openalex.org/W2125785852, https://ope...","[https://openalex.org/W2046765700, https://ope...","{'""critical""': None, '""criticality,""': None, '...","[{'cited_by_count': 148, 'year': 2025}, {'cite...",2025-11-06T03:46:38.306776,2016-06-24T00:00:00,2025-12-15

In [5]:
df_work_raw.dtypes

id                                 object
doi                                object
title                              object
display_name                       object
publication_year                    int64
publication_date                   object
ids                                object
language                           object
primary_location                   object
type                               object
indexed_in                         object
open_access                        object
authorships                        object
institutions                       object
countries_distinct_count            int64
institutions_distinct_count         int64
corresponding_author_ids           object
corresponding_institution_ids      object
apc_list                           object
apc_paid                           object
fwci                              float64
has_fulltext                         bool
cited_by_count                      int64
citation_normalized_percentile     object
cited_by_percentile_year           object
biblio                             object
is_retracted                         bool
is_paratext                          bool
is_xpac                              bool
primary_topic                      object
topics                             object
keywords                           object
concepts                           object
mesh                               object
locations_count                     int64
locations                          object
best_oa_location                   object
sustainable_development_goals      object
awards                             object
funders                            object
has_content                        object
referenced_works_count              int64
referenced_works                   object
related_works                      object
abstract_inverted_index            object
counts_by_year                     object
updated_date                       object
created_date                       object
extract_datetime                   object
dtype: object

# Nodo

In [ ]:
def openalex_load_work(df_work_raw):
    """Limpia y transforma los datos de OpenAlex para su almacenamiento en una base de datos relacional."""
    
    expected_columns = [
        'id',
        # 'doi', # doi existe en ids
        'title',
        'display_name',
        'publication_year',
        'publication_date',
        'ids',
        'language',
        'primary_location',
        'type',
        'type_crossref',
        # 'indexed_in',
        'open_access',
        # 'authorships',
        # 'institution_assertions',
        'countries_distinct_count',
        'institutions_distinct_count',
        # 'corresponding_author_ids',
        # 'corresponding_institution_ids',
        'apc_list',
        'apc_paid',
        'fwci',
        'has_fulltext',
        'fulltext_origin',
        'cited_by_count',
        'citation_normalized_percentile',
        'cited_by_percentile_year',
        'biblio',
        'is_retracted',
        'is_paratext',
        'primary_topic',
        # 'topics',
        # 'keywords',
        # 'concepts',
        # 'mesh',
        'locations_count',
        # 'locations',
        'best_oa_location',
        # 'sustainable_development_goals',
        # 'grants',
        # 'datasets',
        # 'versions',
        'referenced_works_count',
        # 'referenced_works',
        # 'related_works',
        # 'abstract_inverted_index',
        # 'abstract_inverted_index_v3',
        'cited_by_api_url',
        # 'counts_by_year',
        'updated_date',
        'created_date',
        'extract_datetime'
    ]

    df_work = df_work_raw.reindex(columns=expected_columns).reset_index(drop=True).copy()

    # Agregar columnas faltantes con NaN
    for col in expected_columns:
        if col not in df_work.columns:
            df_work[col] = pd.NA

    # ids
    df_ids = pd.json_normalize(df_work['ids']).reset_index(drop=True)
    df_work = pd.concat([df_work, df_ids], axis=1)
    df_work.drop(columns=['ids'], inplace=True)    

    # primary_location
    df_primary_location = pd.json_normalize(df_work['primary_location']).reset_index(drop=True)
    df_primary_location.rename(columns=lambda col: f'primary_location.{col}', inplace=True)
    df_primary_location.drop(columns=[
        'primary_location.source.issn',
        'primary_location.source.host_organization_lineage',
        'primary_location.source.host_organization_lineage_names'
        ],
        inplace=True)

    df_work = pd.concat([df_work, df_primary_location], axis=1)
    df_work.drop(columns=['primary_location'], inplace=True)    

    # openacess
    df_openaccess_expanded = pd.json_normalize(df_work['open_access'])
    df_work = pd.concat([df_work, df_openaccess_expanded], axis=1)
    df_work.drop(columns=['open_access'], inplace=True)    

    # apc_list
    df_apc_list = pd.json_normalize(df_work['apc_list'])
    df_apc_list.rename(columns=lambda col: f'apc_list.{col}', inplace=True)
    df_work = pd.concat([df_work, df_apc_list], axis=1)
    df_work.drop(columns=['apc_list'], inplace=True)    
 
    # apc_paid
    df_apc_paid = pd.json_normalize(df_work['apc_paid'])
    df_apc_paid.rename(columns=lambda col: f'apc_paid.{col}', inplace=True)
    df_work = pd.concat([df_work, df_apc_paid], axis=1)
    df_work.drop(columns=['apc_paid'], inplace=True)    
 
    # citation_normalized_percentile
    df_citation_normalized_percentile = pd.json_normalize(df_work['citation_normalized_percentile'])
    df_citation_normalized_percentile.rename(columns=lambda col: f'citation_normalized_percentile.{col}', inplace=True)
    df_work = pd.concat([df_work, df_citation_normalized_percentile], axis=1)
    df_work.drop(columns=['citation_normalized_percentile'], inplace=True)    

    # cited_by_percentile_year
    df_cited_by_percentile_year = pd.json_normalize(df_work['cited_by_percentile_year'])
    df_cited_by_percentile_year.rename(columns=lambda col: f'cited_by_percentile_year.{col}', inplace=True)
    df_work = pd.concat([df_work, df_cited_by_percentile_year], axis=1)
    df_work.drop(columns=['cited_by_percentile_year'], inplace=True)    

    # biblio
    df_biblio = pd.json_normalize(df_work['biblio'])
    df_biblio.rename(columns=lambda col: f'biblio.{col}', inplace=True)
    df_work = pd.concat([df_work, df_biblio], axis=1)
    df_work.drop(columns=['biblio'], inplace=True)

    # primary_topic
    df_primary_topic = pd.json_normalize(df_work['primary_topic'])
    df_primary_topic.rename(columns=lambda col: f'primary_topic.{col}', inplace=True)
    df_work = pd.concat([df_work, df_primary_topic], axis=1)
    df_work.drop(columns=['primary_topic'], inplace=True)    

    # best_oa_location
    df_best_oa_location = pd.json_normalize(df_work['best_oa_location'])
    df_best_oa_location.rename(columns=lambda col: f'best_oa_location.{col}', inplace=True)
    df_best_oa_location.drop(columns=[
        'best_oa_location.source.host_organization_lineage',
        'best_oa_location.source.host_organization_lineage_names',
        'best_oa_location.source.issn',
    ], inplace=True)
    
    df_work = pd.concat([df_work, df_best_oa_location], axis=1)
    df_work.drop(columns=['best_oa_location'], inplace=True)    

    # Agregar la fecha de carga con formato datetime
    df_work['_load_datetime'] = pd.to_datetime(datetime.today())

    # Convertir tipos de datos automáticamente
    df_work = df_work.convert_dtypes()

    return df_work

## Ejecuto Nodo

In [7]:
df_work = openalex_load_work(df_work_raw)

# Resultados

In [8]:
df_work

,id,title,display_name,publication_year,publication_date,language,type,type_crossref,countries_distinct_count,institutions_distinct_count,fwci,has_fulltext,fulltext_origin,cited_by_count,is_retracted,is_paratext,locations_count,referenced_works_count,cited_by_api_url,updated_date,created_date,extract_datetime,doi,mag,openalex,pmid,primary_location.id,primary_location.is_accepted,primary_location.is_oa,primary_location.is_published,primary_location.landing_page_url,primary_location.license,primary_location.license_id,primary_location.pdf_url,primary_location.raw_source_name,primary_location.raw_type,primary_location.version,primary_location.source.display_name,primary_location.source.host_organization,primary_location.source.host_organization_name,primary_location.source.id,primary_location.source.is_core,primary_location.source.is_in_doaj,primary_location.source.is_oa,primary_location.source.issn_l,primary_location.source.type,any_repository_has_fulltext,is_oa,oa_status,oa_url,apc_list.currency,apc_list.value,apc_list.value_usd,apc_paid.currency,apc_paid.value,apc_paid.value_usd,citation_normalized_percentile.is_in_top_10_percent,citation_normalized_percentile.is_in_top_1_percent,citation_normalized_percentile.value,cited_by_percentile_year.max,cited_by_percentile_year.min,biblio.first_page,biblio.issue,biblio.last_page,biblio.volume,primary_topic.display_name,primary_topic.id,primary_topic.score,primary_topic.domain.display_name,primary_topic.domain.id,primary_topic.field.display_name,primary_topic.field.id,primary_topic.subfield.display_name,primary_topic.subfield.id,best_oa_location.id,best_oa_location.is_accepted,best_oa_location.is_oa,best_oa_location.is_published,best_oa_location.landing_page_url,best_oa_location.license,best_oa_location.license_id,best_oa_location.pdf_url,best_oa_location.raw_source_name,best_oa_location.raw_type,best_oa_location.version,best_oa_location.source.display_name,best_oa_location.source.host_organization,best_oa_location.source.host_organization_name,best_oa_location.source.id,best_oa_location.source.is_core,best_oa_location.source.is_in_doaj,best_oa_location.source.is_oa,best_oa_location.source.issn_l,best_oa_location.source.type,best_oa_location.source,load_datetime
0,https://openalex.org/W2140131090,A global overview of drought and heat-induced ...,A global overview of drought and heat-induced ...,2009,2009-10-22,en,article,<NA>,9,20,93.387205,False,<NA>,7330,False,False,4,251,<NA>,2025-11-06T03:46:38.306776,2025-10-10T00:00:00,2025-12-15,https://doi.org/10.1016/j.foreco.2009.09.001,2140131090,https://openalex.org/W2140131090,<NA>,doi:10.1016/j.foreco.2009.09.001,True,False,True,https://doi.org/10.1016/j.foreco.2009.09.001,<NA>,<NA>,<NA>,Forest Ecology and Management,journal-article,publishedVersion,Forest Ecology and Management,https://openalex.org/P4310320990,Elsevier BV,https://openalex.org/S195255895,True,False,False,0378-1127,journal,False,True,green,https://hal.science/hal-00457602,USD,3460,3460,<NA>,<NA>,<NA>,True,True,0.999836,100,99,660,4,684,259,Fire effects on ecosystems,https://openalex.org/T10555,0.9999,Physical Sciences,https://openalex.org/domains/3,Environmental Science,https://openalex.org/fields/23,Global and Planetary Change,https://openalex.org/subfields/2306,pmh:oai:HAL:hal-00457602v1,False,True,False,https://hal.science/hal-00457602,other-oa,https://openalex.org/licenses/other-oa,<NA>,"Forest Ecology and Management, 2010, 259 (4), ...",Journal articles,submittedVersion,HAL (Le Centre pour la Communication Scientifi...,https://openalex.org/I1294671590,Centre National de la Recherche Scientifique,https://openalex.org/S4306402512,False,False,False,<NA>,repository,<NA>,2026-02-21 12:19:44.290361
1,https://openalex.org/W2762087180,Ferroptosis: A Regulated Cell Death Nexus Link...,Ferroptosis: A Regulated Cell Death Nexus Link...,2017,2017-10-01,en,review,<NA>,6,27,227.560904,False,<NA>,6749,False,False,6,115,<NA>,2025-11-06T03:46:38.306776,2025-10-10T00:00:00,2025-12-15,https://doi.org/10.1016/j.cell.2017.09.021,2762087180,https://openalex.org/W2762087180,https://pubmed.ncbi.nlm.nih.gov/28985560,doi:10.1016/j.cell.2017.09.021,True,True,True,https://doi.org/10.1016/j.cell.2017.09.021,<NA>,<NA>,http://www.cell.com/article/S009286741731070X/pdf,Cell,journal-article,publishedVersion,Cell,https://openalex.org/P4310315673,Cell Press,https://openalex.org/S110447773,True,False,False,0092-8674,journal,False,True,bronze,http://www.cell.com/article/S009286741731070X/pdf,USD,10100,10100,<NA>,<NA>,<NA>,True,True,0.999948,100,90,273,2,285,171,Ferroptosis and cancer prognosis,https://openalex.org/T11297,0.9999,Health Sciences,https://openalex.org/domains/4,Medicine,https://openalex.org/fields/27,Pulmonary and Respiratory Medicine,https://openalex.org/subfields/2740,doi:10.1016/j.cell.2017.09.021,True,True,True,https://doi.org/10.1016/j.cell.2017.09.021,<NA>,<NA>,http://www.cell.com/article/S009286741731070X/pdf,Cell,journal-article,publishedVersion,Cell,https://openalex.org/P4310315673,Cell Press,https://openalex.org/S110447773,True,False,False,0092-8674,journal,<NA>,2026-02-21 12:19:44.290361
2,https://openalex.org/W2151692850,"TNT, a free program for phylogenetic analysis","TNT, a free program for phylogenetic analysis",2008,2008-07-11,en,article,<NA>,3,3,204.217212,False,<NA>,5267,False,False,4,38,<NA>,2025-11-06T03:46:38.306776,2016-06-24T00:00:00,2025-12-15,https://doi.org/10.1111/j.1096-0031.2008.00217.x,2151692850,https://openalex.org/W2151692850,<NA>,doi:10.1111/j.1096-0031.2008.00217.x,True,True,True,https://doi.org/10.1111/j.1096-0031.2008.00217.x,<NA>,<NA>,https://onlinelibrary.wiley.com/doi/pdfdirect/...,Cladistics,journal-article,publishedVersion,Cladistics,https://openalex.org/P4310320595,Wiley,https://openalex.org/S90511721,True,False,False,0748-3007,journal,False,True,bronze,https://onlinelibrary.wiley.com/doi/pdfdirect/...,USD,3810,3810,<NA>,<NA>,<NA>,True,True,1.0,100,99,774,5,786,24,Plant Diversity and Evolution,https://openalex.org/T10385,0.998,Life Sciences,https://openalex.org/domains/1,Agricultural and Biological Sciences,https://openalex.org/fields/11,"Ecology, Evolution, Behavior and Systematics",https://openalex.org/subfields/1105,doi:10.1111/j.1096-0031.2008.00217.x,True,True,True,https://doi.org/10.1111/j.1096-0031.2008.00217.x,<NA>,<NA>,https://onlinelibrary.wiley.com/doi/pdfdirect/...,Cladistics,journal-article,publishedVersion,Cladistics,https://openalex.org/P4310320595,Wiley,https://openalex.org/S90511721,True,False,False,0748-3007,journal,<NA>,2026-02-21 12:19:44.290361
3,https://openalex.org/W2130811469,Global effects of land use on local terrestria...,Global effects of land use on local terrestria...,2015,2015-03-31,en,article,<NA>,5,41,223.54756,False,<NA>,3955,False,False,8,389,<NA>,2025-11-06T03:46:38.306776,2025-10-10T00:00:00,2025-12-15,https://doi.org/10.1038/nature14324,2130811469,https://openalex.org/W2130811469,https://pubmed.ncbi.nlm.nih.gov/25832402,doi:10.1038/nature14324,True,False,True,https://doi.org/10.1038/nature14324,<NA>,<NA>,<NA>,Nature,journal-article,publishedVersion,Nature,https://openalex.org/P4310319908,Nature Portfolio,https://openalex.org/S137773608,True,False,False,0028-0836,journal,False,True,gold,https://durham-repository.worktribe.com/output...,EUR,9750,11690,EUR,9750,11690,True,True,0.999966,100,89,45,7545,50,520,Ecology and Vegetation Dynamics Studies,https://openalex.org/T10005,0.9974,Physical Sciences,https://openalex.org/domains/3,Environmental Science,https://openalex.org/fields/23,Nature and Landscape Conservation,https://openalex.org/subfields/2309,pmh:oai:durham-repository.worktribe.com:1209742,False,True,False,https://durham-repository.worktribe.com/output...,cc-by,https://openalex.org/licenses/cc-by,<NA>,<NA>,Journal Article,submittedVersion,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-02-21 12:19:44.290361
4,https://openalex.org/W4211046286,The ATLAS Experiment at the CERN Large Hadron ...,The ATLAS Experiment at the CERN Large Hadron ...,2008,2008-08-14,en,article,<NA>,36,2048,67.41549,False,<NA>,3910,False,False,15,156,<NA>,2025-11-06T03:46:38.306776,2022-02-13T00:00:00,2025-12-15,https://doi.org/10.1088/1748-0221/3/08/s08003,<NA>,https://openalex.org/W4211046286,<NA>,doi:10.1088/1748-0221/3/08/s08003,True,False,True,https://doi.org/10.1088/1748-0221/3/08/s08003,<NA>,<NA>,<NA>,Journal of Instrumentation,journal-article,publishedVersion,Journal of Instrumentation,https://openalex.org/P4310311669,Institute of Physics,https://openalex.org/S116045149,True,False,False,1748-0221,journal,False,True,green,http://hdl.handle.net/2078.1/138157,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,True,0.999908,100,99,S08003,08,S08003,3,Particle Detector Development and Performance,https://openalex.org/T11044,1.0,Physical Sciences,https://openalex.org/domains/3,Physics and Astronomy,https://openalex.org/fields/31,Nuclear and High Energy Physics,https://openalex.org/subfields/3106,pmh:oai:dial.uclouvain.be:boreal:138157,False,True,False,http://hdl.handle.net/2078.1/138157,other-oa,https://openalex.org/licenses/other-oa,<NA>,"Journal of Instrumentation, Vol. 3, no.--, p. ...",info:eu-repo/semantics/article,submittedVersion,Digital Access to Libraries,https://openalex.org/I2800384882,Harris County Public Library,https://openalex.org/S4306400166,False,False,False,<NA>,repository,<NA>,2026-02-21 12:19:44.290361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,https://openalex.org/W2158724283,Health effects from stratospheric ozone deplet...,Health effects from stratospheric ozone deplet...,2003,2003-01-01,en,review,<NA>,6,8,28.338417,False,<NA>,574,False,False,6,226,<NA>,2025-11-06T03:46:38.306776,2016-06-24T00:00:00,2025-12-15,https://doi.org/10.1039/b211159b,2158724283,https://openalex.org/W2158724283,https://pubmed.ncbi.nlm.nih.gov/12659537,doi:10.1039/b211159b,True,False,True,https://doi.org/10.1039/b211159b,<NA>,<NA>,<NA>,Photochemical &amp; Photobiological Sciences,journal-article,publishedVersion,Photochemical & Photobiological Sciences,https://openalex.org/P4310319900,Springer Science+Business Media,https://openalex.org/S65504228,True,False,False,1474-905X,journal,False,True,green,https://lup.lub.lu.se/record/133488,EUR,2690,3390,<NA>,<NA>,<NA>,True,True,0.997353,100,96,29,1,38,2,Plant responses to elevated CO2,https://openalex.org/T11760,0.9975,Life Sciences,https://openalex.org/domains/1,Agricultural and Biological Sciences,https://openalex.org/fields/11,Plant Science,https://openalex.org/subfields/1110,pmh:oai:lup.lub.lu.se:516b4be4-43f7-4469-85c3-...,False,True,False,https://lup.lub.lu.se/record/133488,other-oa,https://openalex.org/licenses/other-oa,<NA>,ISSN: 1474-9092,text,submittedVersion,Lund University Publications (Lund University),https://openalex.org/I187531555,Lund University,https://openalex.org/S4306400536,False,False,False,<NA>,repository,<NA>,2026-02-21 12:19:44.290361
196,https://openalex.org/W1839088550,Committing to ecological restoration,Committing to ecological restoration,2015,2015-05-07,en,article,<NA>,4,13,158.657698,False,<NA>,573,False,False,2,26,<NA>,2025-11-06T03:46:38.306776,2016-06-24T00:00:00,2025-12-15,https://doi.org/10.1126/science.aaa4216,1839088550,https://openalex.org/W1839088550,https://pubmed.ncbi.nlm.nih.gov/25953995,doi:10.1126/science.aaa4216,True,False,True,https://doi.org/10.1126/science.aaa4216,<NA>,<NA>,<NA>,Science,journal-article,publishedVersion,Science,https://openalex.org/P4310315823,American Association for the Advancement of Sc...,https://openalex.org/S3880285,True,False,False,0036-8075,journal,False,False,closed,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,True,0.999893,100,89,638,6235,640,348,Environmental Conservation and Management,https://openalex.org/T13438,0.9624,Physical Sciences,https://openalex.org/domains/3,Environmental Science,https://openalex.org/fields/23,"Management, Monitoring, Policy and Law",https://openalex.org/subfields/2308,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-02-21 12:19:44.290361
197,https://openalex.org/W3030030520,Gender imbalance in medical imaging datasets p...,Gender imbalance in medical imaging datasets p...,2020,2020-05-26,en,article,<NA>,1,5,25.588486,True,<NA>,572,False,False,3,38,<NA>,2025-11-06T03:46:38.306776,2025-10-10T00:00:00,2025-12-15,https://doi.org/10.1073/pnas.1919012117,3030030520,https://openalex.org/W3030030520,https://pubmed.ncbi.nlm.nih.gov/32457147,doi:10.1073/pnas.1919012117,True,True,True,https://doi.org/10.1073/pnas.1919012117,cc-by,https://openalex.org/licenses/cc-by,https://www.pnas.org/content/pnas/117/23/12592...,Proceedings of the National Academy of Sciences,journal-article,publishedVersion,Proceedings of the National Academy of Sciences,https://openalex.org/P4310320052,National Academy of Sciences,https://openalex.org/S125754415,True,False,False,0027-8424,journal,False,True,hybrid,https://www.pnas.org/content/pnas/117/23/12592...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,True,True,0.994177,100,90,12592,23,12594,117,Artificial Intelligence in Healthcare and Educ...,https://openalex.org/T11636,0.9958,Health Sciences,https://openalex.org/domains/4,Medicine,https://openalex.org/fields/27,Health Informatics,https://openalex.org/subfields/2718,doi:10.1073/pnas.1919012117,True,True,True,https://doi.org/10.1073/pnas.1919012117,cc-by,https://openalex.org/licenses/cc-by,https://www.pnas.org/content/pnas/117/23/12592...,Proceedings of the National Academy of Sciences,journal-article,publishedVersion,Proceedings of the National Academy of Sciences,https://openalex.org/P4310320052,National Academy of Sciences,https://openalex.org/S125754415,True,False,False,0027-8424,journal,<NA>,2026-02-21 12:19:44.290361
198,https://openalex.org/W1989871154,Simulations of Galaxy Formation in a Λ Cold Da...,Simulations of Galaxy Formation in a Λ Cold Da...,2003,2003-10-17,en,article,<NA>,5,8,14.72368,False,<NA>,570,False,False,3,34,<NA>,2025-11-06T03:46:38.306776,2016-06-24T00:00:00,2025-12-15,https://doi.org/10.1086/378316,1989871154,https://openalex.org/W1989871154,<NA>,doi:10.1086/378316,True,True,True,https://doi.org/10.1086/378316,<NA>,<NA>,https://iopscience.iop.org/article/10.1086/378...,The Astrophysical Journal,journal-article,publishedVersion,The Astrophysical Journal,https://openalex.org/P4310320083,IOP Publishing,https://openalex.org/S1980519,True,True,False,0004-637X,journal,False,True,bronze,https://iopscience.iop.org/article/10.1086/378...,USD,4499,4499,<NA>,<NA>,<NA>,True,True,0.993944,100,99,21,1,34,597,"Galaxies: Formation, Evolution, Phenomena",https://openalex.org/T10026,0.9999,Physical Sciences,https://openalex.org/domains/3,Physics and Astronomy,https://openalex.org/fields/31,Astronomy and Astrophysics,https://openalex.org/subfields/3103,doi:10.1086/378316,True,True,True,https://doi.org/10.1086/378316,<NA>,<NA>,https://iopscience.iop.org/article/10.1086/378...,The Astrophysical Journal,journal-article,publishedVersion,The Astrophysical Journal,https://openalex.org/P4310320083,IOP Publishing,https://openalex.org/S1980519,True,True,False,0004-637X,journal,<NA>,2026-02-21 12:19:44.290361
199,https://openalex.org/W3095652295,Solid Lipid Nanoparticles for Drug Delivery: P...,Solid Lipid Nanoparticles for Drug Delivery: P...,2020,2020-10-30,en,review,<NA>,1,3,31.396251,True,<NA>,567,False,False,6,242,<NA>,2025-11-06T03:46:38.306776,2020-11-09T00:00:00,2025-12-15,https://doi.org/10.3389/fmolb.2020.587997,3095652295,https://openalex.org/W3095652295,https://pubmed.ncbi.nlm.nih.gov/33195435,doi:10.3389/fmolb.2020.587997,True,True,True,https://doi.org/10.3389/fmolb.2020.587997,cc-by,https://openalex.org/licenses/cc-by,https://www.frontiersin.org/articles/10.3389/f...,Frontiers in Molecular Biosciences,journal-article,publishedVersion,Frontiers in Molecular Biosciences,https://openalex.org/P4310320527,Frontiers Media,https://openalex.org/S2595797843,True,True,True,2296-889X,journal,False,True,gold,https://www.frontiersin.org/articles/10.3389/f...,USD,2490,2490,USD,2490,2490,True,True,0.999422,100,89,587997,<NA>,587997,7,Advancements in Transdermal Drug Delivery,https://openalex.org/T10704,0.9991,Life Sciences,https://openalex.org/domains/1,"Pharmacology, Toxicology and Pharmaceutics",https://openalex.org/fields/30,Pharmaceutical Science,https://openalex.org/subfields/3003,doi:10.3389/fmolb.2020.587997,True,True,True,https://doi.org/10.3389/fmolb.2020.587997,cc-by,https://openalex.org/licenses/cc-by,https://www.frontiersin.org/articles/10.3389/f...,Frontiers in Molecular Biosciences,journal-article,publishedVersion,Frontiers in Molecular Biosciences,https://openalex.org/P4310320527,Frontiers Media,https://openalex.org/S2595797843,True,True,True,2296-889X,journal,<NA>,2026-02-21 12:19:44.290361